export const Localization = {
  LOGIN: 'Login',
  FACEBOOK_LOGIN: 'FACEBOOK LOGIN',
  NO_CONTENT: 'Sorry! there is not list available',

  FB_LOGIN_CANCELLED: 'Facebook login cancelled',
  FB_LOGIN_FAILED: 'Facebook login failed',
  parseErrorMessage: 'Unable to parse response.',
  apiCallFailedErrorMessage: 'Unable to call api.',

  internalServerErrorMessage: 'The request failed due to an internal server error.',
  serverErrorMessage: 'Sorry, Something Went Wrong: Please try again later.',
  sessionErrorMessage: 'Sorry, Your session has expired. Please login again to continue play.',
  noInternetConnection: {
    header: 'No Internet Connection Available',
    message: 'Please check your internet connection.',
  },
  update: 'Update',
  cancel: 'Cancel',
  loginScreen: {
    LOGIN: 'Login',
    Email: 'Email',
    Password: 'Password',
    ForgotPassword: 'Forgot Password?',
  },
  SignupScreen: {
    Signup: 'Signup',
    ConfirmPassword: 'Confirm Password',
    MobileNumber: 'Mobile Number',
    referalCode: 'Have a Referal Code',
    refererId: 'Referer ID',
    termsAndPolicy: 'I agree with terms conditions and privacy policy',
  },
  homeScreen: {
    Play: 'Play',
    View: 'View',
    TicketBrought: 'Ticket\nBrought',
  },
  myTicketScreen: {
    Live: 'Live',
    Complete: 'Complete',
    All: 'All',
    Win: 'CONGRATULATIONS! YOU WON',
    Loss: 'Better Luck Next Time',
  },
  userProfileScreen: {
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    country: 'Country',
    state: 'State',
    city: 'City',
    address: 'Address',
    zipCode: 'Zip Code',
    selectCountry: 'Select Country',
    selectState: 'Select State',
  },
  myPrizeModelScreen: {
    live: '( Live )',
    complete: '( Completed )',
    youwon: 'You Won',
  },
  NavigationHeader: {
    Logout: 'Logout',
  },
  SaferGamblingScreen: {
    dummyText: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.',
  },
};
