export const Localization = {
  FORGETPASSWORD: 'Forgot Password',
  LOGIN: 'Login',
  FACEBOOK_LOGIN: 'FACEBOOK LOGIN',
  NO_CONTENT: 'Sorry! there is not list available',

  FB_LOGIN_CANCELLED: 'Facebook login cancelled',
  FB_LOGIN_FAILED: 'Facebook login failed',
  parseErrorMessage: 'Unable to parse response.',
  apiCallFailedErrorMessage: 'Unable to call api.',
  emptyEmailErrorMessage: 'Please enter email address.',
  invalidEmailErrorMessage: 'Your e-mail is incorrect.',
  emptyMobileNumberErrorMessage: 'Please enter mobile number.',
  mobileNumberLengthError: 'Mobile number must have length ranging from 5 to 15',
  emptyPasswordErrorMessage: 'Please enter password.',
  passwordLengthError: 'Password must be atleast 6 characters in length',
  passwordDoNotMatch: 'Passwords do not match',
  referalCodeIsRequired: 'Referal code is required',
  termsAndConditionNotChecked: 'Please accept Terms and Conditions to continue',
  internalServerErrorMessage: 'The request failed due to an internal server error.',
  serverErrorMessage: 'Sorry, Something Went Wrong: Please try again later.',
  sessionErrorMessage: 'Sorry, Your session has expired. Please login again to continue play.',
  noInternetConnection: {
    header: 'No Internet Connection Available',
    message: 'Please check your internet connection.',
  },
  alert: 'Alert',
  update: 'Update',
  cancel: 'Cancel',
  loginScreen: {
    LOGIN: 'Login',
    Email: 'Email',
    Password: 'Password',
    ForgotPassword: 'Forgot Password?',
    RememberPassword: 'Remember Your Password, Login ?',
    ResetPassword: 'Reset Password',
  },
  SignupScreen: {
    Signup: 'Signup',
    ConfirmPassword: 'Confirm Password',
    MobileNumber: 'Mobile Number',
    referalCode: 'Have a Referal Code',
    refererId: 'Referer ID',
    termsAndPolicy: 'I agree with terms conditions and privacy policy',
  },
  ChangePasswordScreen: {
    ChangePassword: 'Change Password',
    ConfirmPassword: 'Confirm Password',
    OldPassword: 'Old Password',
    NewPassword: 'New Password',
    UpdatePassword: 'Update Password',
  },
  homeScreen: {
    Play: 'Play',
    View: 'View',
    TicketBrought: 'Ticket\nBrought',
  },
  myTicketScreen: {
    Live: 'Live',
    Complete: 'Complete',
    All: 'All',
    Win: 'CONGRATULATIONS! YOU WON',
    Loss: 'Better Luck Next Time',
    searchByName: 'Search by Lottery name',
  },
  userProfileScreen: {
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    country: 'Country',
    state: 'State',
    city: 'City',
    address: 'Address',
    zipCode: 'Zip Code',
    selectCountry: 'Select Country',
    selectState: 'Select State',
  },
  myPrizeModelScreen: {
    live: '( Live )',
    complete: '( Completed )',
    youwon: 'You Won',
  },
  NavigationHeader: {
    Logout: 'Logout',
    SaferGambling: ' Safer Gambling',
  },
  SaferGamblingScreen: {
    dummyText: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.',
  },
  myTicketDetailsScreen: {
    Name: 'Name',
    TicketPrice: 'Ticket Price',
    TicketBought: 'Ticket Bought',
    Prizes: 'Prizes',
    Play: 'Play',
    Ticket: 'Ticket',
    Boughtat: 'Bought at',
    Print: 'Print',
    serialNo: '#',
  },
  DisputeReason: {
    DisputeReason: 'Dispute Reason',
    Submit: 'Submit',
  },
};
