export const Localization = {
  FORGETPASSWORD: 'Forgot Password',
  LOGIN: 'Login',
  FACEBOOK_LOGIN: 'FACEBOOK LOGIN',
  NO_CONTENT: 'Sorry! there is not list available',

  FB_LOGIN_CANCELLED: 'Facebook login cancelled',
  FB_LOGIN_FAILED: 'Facebook login failed',
  parseErrorMessage: 'Unable to parse response.',
  apiCallFailedErrorMessage: 'Unable to call api.',
  emptyEmailErrorMessage: 'Please enter email address.',
  invalidEmailErrorMessage: 'Your e-mail is incorrect.',
  emptyUserNameErrorMessage: 'Username is required.',
  invalidUserNameErrorMessage: 'Username must begin with a letter and must only contain alphanumeric characters and contain only one _(underscore).',
  emptyZipCodeErrorMessage: 'Zip Code is required.',
  invalidZipCodeErrorMessage: ' Zipcode must only contain alphanumeric characters and must have at least 3 characters.',
  emptyFirstNameErrorMessage: 'Firstname is required.',
  invalidFirstNameErrorMessage: 'Firstname must only contain characters and must have at least 2 characters.',
  emptyLastNameErrorMessage: 'Lastname is required.',
  invalidLastNameErrorMessage: 'Lastname must only contain characters and must have at least 2 characters.',
  emptyCityErrorMessage: 'City is required.',
  invalidCityErrorMessage: 'City must only contain characters and must have at least 2 characters.',
  emptyAddressErrorMessage: 'Address is required.',
  invalidAddressErrorMessage: 'Address must have at least 5 characters.',
  emptyCountryErrorMessage: 'Country is required.',
  emptyDobErrorMessage: 'Dob is required',
  emptyStateErrorMessage: 'State is required.',
  emptyMobileNumberErrorMessage: 'Please enter mobile number.',
  mobileNumberLengthError: 'Mobile number must have length ranging from 5 to 15',
  emptyPasswordErrorMessage: 'Please enter password.',
  passwordLengthError: 'Password must be atleast 6 characters in length',
  passwordDoNotMatch: 'Passwords do not match',
  referalCodeIsRequired: 'Referal code is required',
  termsAndConditionNotChecked: 'Please accept Terms and Conditions to continue',
  internalServerErrorMessage: 'The request failed due to an internal server error.',
  serverErrorMessage: 'Sorry, Something Went Wrong: Please try again later.',
  sessionErrorMessage: 'Sorry, Your session has expired. Please login again to continue play.',
  noInternetConnection: {
    header: 'No Internet Connection Available',
    message: 'Please check your internet connection.',
  },
  alert: 'Alert',
  update: 'Update',
  cancel: 'Cancel',
  loginScreen: {
    LOGIN: 'Login',
    Email: 'Email',
    Password: 'Password',
    ForgotPassword: 'Forgot Password?',
    RememberPassword: 'Remember Your Password, Login ?',
    ResetPassword: 'Reset Password',
  },
  SignupScreen: {
    Signup: 'Signup',
    ConfirmPassword: 'Confirm Password',
    MobileNumber: 'Mobile Number',
    referalCode: 'Have a Referal Code',
    refererId: 'Referer ID',
    termsAndPolicy: 'I agree with terms conditions and privacy policy',
  },
  ChangePasswordScreen: {
    ChangePassword: 'Change Password',
    ConfirmPassword: 'Confirm Password',
    OldPassword: 'Old Password',
    NewPassword: 'New Password',
    UpdatePassword: 'Update Password',
  },
  homeScreen: {
    Play: 'Play',
    View: 'View',
    TicketBrought: 'Ticket\nBrought',
  },
  myTicketScreen: {
    Live: 'Live',
    Completed: 'Completed',
    All: 'All',
    Win: 'CONGRATULATIONS! YOU WON',
    Loss: 'Better Luck Next Time',
    searchByName: 'Search by Lottery name',
  },
  userProfileScreen: {
    firstName: 'First Name',
    lastName: 'Last Name',
    dateOfBirth: 'Date of Birth',
    gender: 'Gender',
    country: 'Country',
    state: 'State',
    city: 'City',
    address: 'Address',
    selectCountry: 'Select Country',
    selectState: 'Select State',
    inviteFriend: 'Invite Friend',
    invite: 'Invite',
  },
  myPrizeModelScreen: {
    live: '( Live )',
    complete: '( Completed )',
    youwon: 'You Won',
  },
  NavigationHeader: {
    Logout: 'Logout',
    SaferGambling: ' Safer Gambling',
  },
  SaferGamblingScreen: {
    dummyText: 'Lorem ipsum, or lipsum as it is sometimes known, is dummy text used in laying out print, graphic or web designs. The passage is attributed to an unknown typesetter in the 15th century who is thought to have scrambled parts of Cicero\'s De Finibus Bonorum et Malorum for use in a type specimen book.',
  },
  myTicketDetailsScreen: {
    Name: 'Name',
    TicketPrice: 'Ticket Price',
    TicketBought: 'Ticket Bought',
    Prizes: 'Prizes',
    Play: 'Play',
    Ticket: 'Ticket',
    Boughtat: 'Bought at',
    Print: 'Print',
    serialNo: '#',
  },
  inviteFriend: {
    date: 'DATE',
    email: 'EMAIL',
    status: 'STATUS',
    pending: 'Pending',
    accept: 'Accept',
  },
  DisputeReason: {
    DisputeReason: 'Dispute Reason',
    Submit: 'Submit',
  },
  SideMenu: {
    AboutUs: 'ABOUT US',
    HowToPlay: 'HOW TO PLAY',
    Help: 'HELP',
    GameRules: 'GAME RULES',
    FAQs: 'FAQs',
    TermsContions: 'TERMS & CONDITIONS',
    PrivacyPolicy: 'PRIVACY POLICY',
    Copyright: 'Copyright © 2020 Car lottery Company. All rights reserved.',
  },
  Transaction: {
    amount: 'AMOUNT',
    Transaction: 'TRANSACTION',
    date: 'DATE',
    // TransactionId: 'TRANSACTION ID',
    description: 'DESCRIPTION',
    status: 'STATUS',
  },
};
