import { bindActionCreators } from 'redux';
import { store } from '../store';

import {
  getSportsRequest,
  getSportsSuccess,
  getSportsFailure,
  loginRequest,
  registerRequest,
  logoutRequest,
  logoutSuccess,
  logoutFailure,
  forgetpasswordFailure,
  forgetpasswordRequest,
  forgetpasswordSuccess,
  changepasswordFailure,
  changepasswordRequest,
  changepasswordSuccess,
  openLoginView,
  openAuthForgotPasswordView,
} from './authenticationActions';

import {
  getCountryRequest,
  getCountrySuccess,
  getCountryFailure,

  getStateRequest,
  getStateSuccess,
  getStateFailure,

  getProfileRequest,
  getProfileFailure,
  getProfileSuccess,

  updateProfileRequest,
  updateProfileSuccess,
  updateProfileFailure,

  setUserProfileImage,

  getTransactionsRequest,
  getTransactionsSuccess,
  getTransactionsFailure,

} from './profileActions';

import {
  updateLobbyCurrentPage,
  // my tickets
  myTicketsFilterRequest,
  myTicketsFilterSuccess,
  myTicketsFilterFailure,
  getMyLotteriesRequest,
  getMyLotteriesSuccess,
  getMyLotteriesFailure,
  getLotterieWinnersRequest,
  getLotterieWinnersSuccess,
  getLotterieWinnersFailure,
  getUserWinnerTicketsRequest,
  getUserWinnerTicketsSuccess,
  getUserWinnerTicketsFailure,
  getHotLotteriesRequest,
  getHotLotteriesSuccess,
  getHotLotteriesFailure,
  myTicketsContestDetailsSuccess,
  myTicketsContestDetailsRequest,
  myTicketsContestDetailsFailure,
  getUserContestDetailsFailure,
  getUserContestDetailsRequest,
  getUserContestDetailsSuccess,
  // lobby
  lobbyFilterRequest,
  lobbyFilterSuccess,
  lobbyFilterFailure,
  getLobbyHotLotteriesRequest,
  getLobbyHotLotteriesSuccess,
  getLobbyHotLotteriesFailure,

  joinLotteryRequest,
  joinLotterySuccess,
  joinLotteryFailure,
  updatedMyTickets,
  printTicketsRequest,
  printTicketsSuccess,
  printTicketsFailure,

  // dispute
  disputeFailure,
  disputeRequest,
  disputeSuccess,
} from './dashboardActions';

import {
  getDepositLimitMonthsRequest,
  getDepositLimitMonthsSuccess,
  getDepositLimitMonthsFailure,
  getDepositLimitWeeksRequest,
  getDepositLimitWeeksSuccess,
  getDepositLimitWeeksFailure,
  getDepositLimitDaysRequest,
  getDepositLimitDaysSuccess,
  getDepositLimitDaysFailure,
  getWagerLimitMonthsRequest,
  getWagerLimitMonthsSuccess,
  getWagerLimitMonthsFailure,
  getWagerLimitWeeksRequest,
  getWagerLimitWeeksSuccess,
  getWagerLimitWeeksFailure,
  getWagerLimitDaysRequest,
  getWagerLimitDaysSuccess,
  getWagerLimitDaysFailure,
  setDepositLimitMonthsRequest,
  setDepositLimitMonthsSuccess,
  setDepositLimitMonthsFailure,
  setDepositLimitWeeksRequest,
  setDepositLimitWeeksSuccess,
  setDepositLimitWeeksFailure,
  setDepositLimitDaysRequest,
  setDepositLimitDaysSuccess,
  setDepositLimitDaysFailure,
  setWagerLimitMonthsRequest,
  setWagerLimitMonthsSuccess,
  setWagerLimitMonthsFailure,
  setWagerLimitWeeksRequest,
  setWagerLimitWeeksSuccess,
  setWagerLimitWeeksFailure,
  setWagerLimitDaysRequest,
  setWagerLimitDaysSuccess,
  setWagerLimitDaysFailure,
  deleteDepositLimitRequest,
  deleteDepositLimitFailure,
  deleteDepositLimitSuccess,
  deleteWagerLimitFailure,
  deleteWagerLimitRequest,
  deleteWagerLimitSuccess,
  selfTimeoutRequest,
  selfTimeoutFailure,
  selfTimeoutSuccess,
  suspendUserRequest,
  suspendUserSuccess,
  suspendUserFailure,
} from './saferGamblingActions';

import {
  getHeaderAdRequest,
  getHeaderAdSuccess,
  getHeaderAdFailure,
  getFooterAdRequest,
  getFooterAdFailure,
  getFooterAdSuccess,
} from './advertisementActions';

const actions = {
  getSportsRequest,
  getSportsSuccess,
  getSportsFailure,
  loginRequest,
  registerRequest,
  getHotLotteriesRequest,
  getHotLotteriesSuccess,
  getHotLotteriesFailure,
  lobbyFilterRequest,
  lobbyFilterSuccess,
  lobbyFilterFailure,
  getLobbyHotLotteriesRequest,
  getLobbyHotLotteriesSuccess,
  getLobbyHotLotteriesFailure,
  getCountryRequest,
  getCountrySuccess,
  getCountryFailure,
  getStateRequest,
  getStateSuccess,
  getStateFailure,
  getProfileRequest,
  getProfileFailure,
  getProfileSuccess,
  updateProfileRequest,
  updateProfileSuccess,
  updateProfileFailure,
  setUserProfileImage,
  joinLotteryRequest,
  joinLotterySuccess,
  joinLotteryFailure,
  updatedMyTickets,
  updateLobbyCurrentPage,
  myTicketsFilterRequest,
  myTicketsFilterSuccess,
  myTicketsFilterFailure,
  getMyLotteriesRequest,
  getMyLotteriesSuccess,
  getMyLotteriesFailure,
  logoutRequest,
  logoutSuccess,
  logoutFailure,
  changepasswordFailure,
  changepasswordRequest,
  changepasswordSuccess,
  forgetpasswordRequest,
  forgetpasswordFailure,
  forgetpasswordSuccess,
  getLotterieWinnersRequest,
  getLotterieWinnersSuccess,
  getLotterieWinnersFailure,
  getUserContestDetailsFailure,
  getUserContestDetailsRequest,
  getUserContestDetailsSuccess,
  getUserWinnerTicketsRequest,
  getUserWinnerTicketsSuccess,
  getUserWinnerTicketsFailure,
  myTicketsContestDetailsSuccess,
  myTicketsContestDetailsFailure,
  myTicketsContestDetailsRequest,
  printTicketsRequest,
  printTicketsSuccess,
  printTicketsFailure,
  disputeSuccess,
  disputeRequest,
  disputeFailure,
  // safe gambling
  getDepositLimitMonthsRequest,
  getDepositLimitMonthsSuccess,
  getDepositLimitMonthsFailure,
  getDepositLimitWeeksRequest,
  getDepositLimitWeeksSuccess,
  getDepositLimitWeeksFailure,
  getDepositLimitDaysRequest,
  getDepositLimitDaysSuccess,
  getDepositLimitDaysFailure,
  getWagerLimitMonthsRequest,
  getWagerLimitMonthsSuccess,
  getWagerLimitMonthsFailure,
  getWagerLimitWeeksRequest,
  getWagerLimitWeeksSuccess,
  getWagerLimitWeeksFailure,
  getWagerLimitDaysRequest,
  getWagerLimitDaysSuccess,
  getWagerLimitDaysFailure,
  setDepositLimitMonthsRequest,
  setDepositLimitMonthsSuccess,
  setDepositLimitMonthsFailure,
  setDepositLimitWeeksRequest,
  setDepositLimitWeeksSuccess,
  setDepositLimitWeeksFailure,
  setDepositLimitDaysRequest,
  setDepositLimitDaysSuccess,
  setDepositLimitDaysFailure,
  setWagerLimitMonthsRequest,
  setWagerLimitMonthsSuccess,
  setWagerLimitMonthsFailure,
  setWagerLimitWeeksRequest,
  setWagerLimitWeeksSuccess,
  setWagerLimitWeeksFailure,
  setWagerLimitDaysRequest,
  setWagerLimitDaysSuccess,
  setWagerLimitDaysFailure,
  deleteDepositLimitRequest,
  deleteDepositLimitFailure,
  deleteDepositLimitSuccess,
  deleteWagerLimitFailure,
  deleteWagerLimitRequest,
  deleteWagerLimitSuccess,
  selfTimeoutRequest,
  selfTimeoutFailure,
  selfTimeoutSuccess,
  suspendUserRequest,
  suspendUserSuccess,
  suspendUserFailure,
  openLoginView,
  openAuthForgotPasswordView,
  // advertisement
  getHeaderAdRequest,
  getHeaderAdSuccess,
  getHeaderAdFailure,
  getFooterAdRequest,
  getFooterAdFailure,
  getFooterAdSuccess,
  getTransactionsRequest,
  getTransactionsSuccess,
  getTransactionsFailure,
};

export default bindActionCreators(actions, store.dispatch);
